version: "3"
services:
  smokeping-speedtest:
    build:
      context: https://github.com/1n6w3coza/docker-smokeping-speedtest-install.git
      dockerfile: Dockerfile
    image: smokeping-speedtest:local
    container_name: smokeping-speedtest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /opt/smokeping-speedtest/config:/config
      - /opt/smokeping-speedtest/data:/data
    ports:
      - 80:80
    restart: unless-stopped
