---
version: "2.1"
services:
  smokeping-speedtest:
    image: jwigley/smokeping-speedtest
    container_name: smokeping-speedtest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /opt/smokeping-speedtest/config:/config
      - /opt/smokeping-speedtest/data:/data
    ports:
      - 80:80
    restart: unless-stopped
